version: "3.8"
   
services:
  rest-1:
    build: .
    command: npm run start
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: "db"
    ports:
      - "80:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - default

  db:
    image: postgres
    environment:
      - POSTGRES_DB=vinyls
      - POSTGRES_USER=postgres_navidupli
      - POSTGRES_PASSWORD=postgres_navidupli
    ports:
      - "5454:5432"
    networks:
      - default
